name: 'Deployment: Development'

run-name: 'Deployment: Development to ${{ inputs.country }} by @${{ github.actor }}'

on:
  push:
    branches:
      - development
    tags-ignore:
      - '*'  
  workflow_dispatch:
    inputs:
      country:
        description: 'Country deployment'
        required: true
        default: 'chile'
        type: choice
        options:
        - chile
        - spain
        - costarica
        - LATAM
        - EUROPE
        - CA
        - all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.country }}
  cancel-in-progress: false

env:
  application: core
  environment: development

jobs:
  cd:
    name: ${{ matrix.icon }} Deployment ${{ matrix.country }}
    runs-on: "ubuntu-20.04"
    if: github.ref == 'refs/heads/development' || (github.ref == 'refs/heads/development' && ${{ github.event.inputs.country }}) || (github.ref == 'refs/heads/development' && github.event_name == 'pull_request' && github.event.pull_request.merged)
    strategy:
      matrix:
        include:
           - country: chile
             aws-region: us-east-1
             region: ["LATAM"]
             icon: 🇨🇱
           - country: spain
             aws-region: eu-west-1
             region: ["EUROPE"]
             icon: 🇪🇸
           - country: costarica
             aws-region: us-east-1
             region: ["LATAM", "CA"]
             icon: 🇨🇷
         
    steps:
      - name: Test
        if: |
          matrix.country == inputs.country  ||
          matrix.region[0] == inputs.country ||
          matrix.region[1] == inputs.country ||
          inputs.country == 'all' ||
          (github.ref == 'refs/heads/development' && github.event_name == 'push')
        run: sleep 10 && echo "This is a test from ${{ matrix.country }}"
