name: Test

on:
  workflow_dispatch:
    inputs:
      country:
        description: 'Country deployment'
        required: true
        default: 'chile'
        type: choice
        options:
        - chile

jobs:
  build:

    runs-on: "ubuntu-20.04"

    if: |
      github.actor == 'brvolpini' &&
      startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Test
      run: echo "This is a test"
