name: 'Deployment: Development'

run-name: 'Deployment: Development to ${{ inputs.country }} by @${{ github.actor }}'

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'  
  workflow_dispatch:
    inputs:
      country:
        description: 'Country deployment'
        required: true
        default: 'guatemala'
        type: choice
        options:
        - chile
        - spain
        - costarica
        - LATAM
        - EUROPE
        - CA
        - all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.country }}
  cancel-in-progress: false

env:
  application: core
  environment: development

jobs:
  cd:
    name: ${{ matrix.icon }} Deployment ${{ matrix.country }}
    runs-on: "ubuntu-20.04"
    strategy:
      matrix:
        include:
           - country: chile
             aws-region: us-east-1
             region: ["LATAM"]
             icon: 🇨🇱
           - country: spain
             aws-region: eu-west-1
             region: ["EUROPE"]
             icon: 🇪🇸
           - country: costarica
             aws-region: us-east-1
             region: ["LATAM", "CA"]
             icon: 🇨🇷
         
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Test
        run: |
          echo "This is a test from ${{ matrix.country }}\n" >> salida.txt
      - name: upload artifact
        uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: ./salida.txt

  push_changes:
    needs: cd
    runs-on: "ubuntu-20.04"
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: my-artifact
          path: /home/runner/work/mydocker/mydocker/salida.txt

      - name: Commit files
        run: |
            cat /home/runner/work/mydocker/mydocker/salida.txt/salida.txt > README.md
            git config --local user.email ${{ secrets.GIT_EMAIL }}
            git config --local user.name ${{ secrets.GIT_USER }}
            git add .
            git commit -a -m "Add changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          force_with_lease: true
      